### ISSUE TITLE
jinja2-time install seems to be broken due arrow

### ISSUE THREAD

**Issue by wilmardo** [hackebrot/jinja2-time#6]
Broken on at least Python 2.7 due to [this issue at `arrow`](https://github.com/crsmithdev/arrow/issues/495).  PR #5 seems really necessary now!

For the install logs see [my comment in the PR over at `arrow`](https://github.com/crsmithdev/arrow/issues/495#issuecomment-375348361)
<details>
<summary>test import</summary>

```
wilmardo@NUC-FLEX-01:/mnt/c/Users/wilmaro/Documents/Ubuntu$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from jinja2 import Environment
>>> env = Environment(extensions=['jinja2_time.TimeExtension'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wilmardo/.local/lib/python2.7/site-packages/jinja2/environment.py", line 333, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/home/wilmardo/.local/lib/python2.7/site-packages/jinja2/environment.py", line 85, in load_extensions
    extension = import_string(extension)
  File "/home/wilmardo/.local/lib/python2.7/site-packages/jinja2/utils.py", line 143, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
  File "/home/wilmardo/.local/lib/python2.7/site-packages/jinja2_time/__init__.py", line 3, in <module>
    from .jinja2_time import TimeExtension
  File "/home/wilmardo/.local/lib/python2.7/site-packages/jinja2_time/jinja2_time.py", line 3, in <module>
    import arrow
  File "/home/wilmardo/.local/lib/python2.7/site-packages/arrow/__init__.py", line 3, in <module>
    from .arrow import Arrow
  File "/home/wilmardo/.local/lib/python2.7/site-packages/arrow/arrow.py", line 19, in <module>
    from arrow import util, locales, parser, formatter
  File "/home/wilmardo/.local/lib/python2.7/site-packages/arrow/parser.py", line 12, in <module>
    from backports.functools_lru_cache import lru_cache  # pragma: no cover
ImportError: No module named functools_lru_cache
```

</details>

**Comment by sscherfke** [comment]
What about replacing arrow with [Pendulum](https://pendulum.eustace.io/)?  What I’ve heard and experienced so far, it would be a good alternative.

**Comment by sscherfke** [comment]
I could create a PR for this.
